### ISSUE TITLE
Lista de árboles con datos completos

### ISSUE THREAD

**Issue by kaametza** [arbio/Adopta-Arbol#16]
Debemos filtrar la lista y solo presentar al usuario final aquellos árboles que cuenten con los datos mínimos de nombre, altura y diámetro.

**Comment by icarito** [comment]
https://github.com/arbio/Adopta-Arbol/blob/d39279f6633aefbc123c4dc1c53e8180aa3f587d/adoptarbol/tree/models.py#L131

Actualmente estaba mostrando sólo los que tuviesen diámetro y posición geográfica, pero bien, incluiremos altura y nombre.

**Comment by icarito** [comment]
Arreglado en 8d2b5c95e0e3a4056db7a848bebe87b0528f2605
