### ISSUE TITLE
Reinventar la lista / mapa

### ISSUE THREAD

**Issue by icarito** [arbio/Adopta-Arbol#8]
La lista fue usada para escoger árboles sin revelar su ubicación. Hace falta una forma más creativa de visualizar los árboles, usando ubicaciones relativas (no el mapa con el dato exacto GPS)

**Comment by icarito** [comment]
@kaametza @tatiespinosa7 lo ideal aquí es una pieza gráfica / artística - hemos priorizado la funcionalidad básica ahora se puede afinar el aspecto gráfico

**Comment by icarito** [comment]
He actualizado para incluir una primera implementación de mapa:
![image](https://user-images.githubusercontent.com/199755/35406482-099e809c-01d7-11e8-8bed-6b9d2af39c02.png)

Se puede ver en http://arbio.somosazucar.org/trees#

Quedaría resolver:
* [ ] - la carga de los datos correctos #6 
* [ ] - listar árboles por proximidad (geo query)
* [ ] - zoom automático para selección de árboles

**Comment by icarito** [comment]
También confirmar que este tipo de visualización es lo más preferible.

**Comment by tatiespinosa7** [comment]
Hola Sebastian.
Sí, creo que esa visualización es una buena opción. Me comentaste que no
tenian las fotos del censo? Es así?  Me confirmas para pasartelas por
wetransfer.


El ene. 25, 2018 2:01 PM, "Sebastian Silva" <notifications@github.com>
escribió:

También confirmar que este tipo de visualización es lo más preferible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arbio/Adopta-Arbol/issues/8#issuecomment-360565609>,
or mute
the thread

**Comment by tatiespinosa7** [comment]
Si no cargaron la base de datos correcta, como hacemos...  les paso de
nuevo la base de datos y una carpeta con todas las fotos?  Me dicen

**Comment by kaametza** [comment]
@icarito @tatiespinosa7  
Pienso que sería conveniente (1) indicar en que página de la lista vamos y (2) disponibilizar la opción de minimizar el carrito de adopción para continuar "navegando" con mas espacio en la pantalla

**Comment by kaametza** [comment]
"Adopta un árbol Amazónico" es un mensaje fácil de transmitir por lo que sugiero que el mapa tenga ajustado el zoom en la Cuenca Amazónica para la primera visualización. Podemos pensar en una transición animada a un mayor nivel de Zoom?

**Comment by icarito** [comment]
Bien, aquí documento para una exploración futura, es una visualización 3D libre llamada [Cesium](https://cesiumjs.org/demos/):

![image](https://user-images.githubusercontent.com/199755/36240167-bca886b8-11dd-11e8-8f69-26e1ca32b28f.png)
![image](https://user-images.githubusercontent.com/199755/36240168-c3125376-11dd-11e8-9736-e3edb153dbde.png)
![image](https://user-images.githubusercontent.com/199755/36240181-df5a5a92-11dd-11e8-8f48-a6806e91b1a8.png)

Combinado con un [modelador de árboles](http://ngplant.org/):
![image](https://user-images.githubusercontent.com/199755/36240125-438bc8bc-11dd-11e8-9c8b-3c6ccac17b12.png)
![image](https://user-images.githubusercontent.com/199755/36240205-0620d066-11de-11e8-8d87-1eea90795ae6.png)
